# Generated by Django 5.2.1 on 2025-05-08 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer_name', models.CharField(max_length=100, verbose_name='스트리머 이름')),
                ('character_name', models.CharField(max_length=100, verbose_name='캐릭터 이름')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '스트리머 캐릭터',
                'verbose_name_plural': '스트리머 캐릭터 목록',
            },
        ),
        migrations.CreateModel(
            name='CharacterRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=20, verbose_name='서버')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='랭킹')),
                ('character_class', models.CharField(max_length=20, verbose_name='클래스')),
                ('combat_power', models.IntegerField(verbose_name='전투력')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='마지막 업데이트')),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.streamercharacter', verbose_name='스트리머')),
            ],
            options={
                'verbose_name': '캐릭터 랭킹',
                'verbose_name_plural': '캐릭터 랭킹 목록',
                'ordering': ['-combat_power'],
            },
        ),
    ]
