# Generated by Django 5.2.1 on 2025-05-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterranking',
            name='class_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='클래스 명명'),
        ),
    ]
