# Generated by Django 5.2.1 on 2025-05-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_characterranking_class_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamercharacter',
            name='server',
            field=models.CharField(choices=[('데이안', '데이안'), ('아이라', '아이라'), ('던컨', '던컨'), ('알리사', '알리사'), ('메이븐', '메이븐'), ('라사', '라사'), ('칼릭스', '칼릭스')], default='데이안', max_length=20, verbose_name='서버'),
        ),
        migrations.AlterField(
            model_name='streamercharacter',
            name='character_name',
            field=models.CharField(max_length=50, verbose_name='캐릭터 이름'),
        ),
        migrations.AlterField(
            model_name='streamercharacter',
            name='streamer_name',
            field=models.CharField(max_length=50, verbose_name='스트리머 이름'),
        ),
    ]
