# Generated by Django 5.2.1 on 2025-05-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_streamercharacter_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterranking',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
    ]
